import type { Walkthrough } from "../../core/src/types.js";

const escapeHtml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const escapeComment = (value: string): string => value.replaceAll("--", "- -");

export function buildEmbedHtml(
  frames: Buffer[],
  fps: number,
  walkthrough: Walkthrough,
): string {
  const rawTitle = walkthrough.title ?? "Walkr Capture";
  const title = escapeHtml(rawTitle);
  const commentTitle = escapeComment(rawTitle);
  const safeFps = Number.isFinite(fps) && fps > 0 ? Math.round(fps) : 30;
  const frameData = frames.map((frame) => `data:image/png;base64,${frame.toString("base64")}`);
  const maxFrame = Math.max(frameData.length - 1, 0);

  return `<!-- Generated by Walkr v0.1.0 | Title: ${commentTitle} | Frames: ${frameData.length} | FPS: ${safeFps} -->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
* {
  box-sizing: border-box;
}
body {
  margin: 0;
  min-height: 100dvh;
  font-family: "Avenir Next", "Segoe UI", "Helvetica Neue", sans-serif;
  color: #f8fafc;
  background:
    radial-gradient(1200px 600px at 20% -10%, rgba(56, 189, 248, 0.28), transparent 60%),
    radial-gradient(900px 500px at 95% 100%, rgba(45, 212, 191, 0.22), transparent 55%),
    linear-gradient(160deg, #030712 0%, #0f172a 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 20px;
}
.player {
  width: min(1120px, 100%);
  background: rgba(15, 23, 42, 0.58);
  border: 1px solid rgba(148, 163, 184, 0.24);
  border-radius: 18px;
  overflow: hidden;
  box-shadow: 0 28px 70px rgba(2, 6, 23, 0.55);
  backdrop-filter: blur(12px);
}
.player-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 14px 16px;
  border-bottom: 1px solid rgba(148, 163, 184, 0.18);
  background: linear-gradient(180deg, rgba(15, 23, 42, 0.78), rgba(15, 23, 42, 0.42));
}
.title-row {
  display: flex;
  align-items: center;
  gap: 10px;
  min-width: 0;
}
.title {
  margin: 0;
  font-size: 14px;
  line-height: 1.4;
  font-weight: 700;
  color: #e2e8f0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.badge {
  font-size: 11px;
  line-height: 1;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: #cbd5e1;
  background: rgba(15, 23, 42, 0.9);
  border: 1px solid rgba(148, 163, 184, 0.3);
  border-radius: 999px;
  padding: 5px 8px;
}
.copy-link {
  border: 1px solid rgba(125, 211, 252, 0.5);
  color: #e0f2fe;
  background: rgba(2, 132, 199, 0.24);
  border-radius: 999px;
  padding: 7px 12px;
  font-size: 12px;
  font-weight: 700;
  cursor: pointer;
}
.frame-display {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  min-height: 280px;
  background: #020617;
}
#frame {
  width: 100%;
  height: 100%;
  display: block;
  object-fit: contain;
  opacity: 1;
  transition: opacity 120ms ease-out;
}
.is-swapping {
  opacity: 0.94;
}
.loading {
  position: absolute;
  inset: 0;
  display: grid;
  place-items: center;
  background: rgba(2, 6, 23, 0.62);
  color: #e2e8f0;
  font-size: 13px;
  letter-spacing: 0.01em;
}
.loading.hidden {
  display: none;
}
.loading-label {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border-radius: 999px;
  border: 1px solid rgba(148, 163, 184, 0.3);
  background: rgba(15, 23, 42, 0.9);
}
.loading-label::before {
  content: "";
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: #22d3ee;
  animation: pulse 1s ease-in-out infinite;
}
@keyframes pulse {
  0%, 100% { transform: scale(0.8); opacity: 0.6; }
  50% { transform: scale(1); opacity: 1; }
}
.controls {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  align-items: center;
  padding: 12px 16px 16px;
  border-top: 1px solid rgba(148, 163, 184, 0.16);
  background: rgba(15, 23, 42, 0.46);
}
.left-controls {
  display: inline-flex;
  align-items: center;
  gap: 8px;
}
.control-btn {
  width: 34px;
  height: 34px;
  border: 1px solid rgba(148, 163, 184, 0.4);
  border-radius: 999px;
  background: rgba(15, 23, 42, 0.86);
  color: #e2e8f0;
  cursor: pointer;
  font-size: 14px;
  font-weight: 700;
}
.control-btn:hover {
  background: rgba(30, 41, 59, 0.95);
}
.progress-wrap {
  flex: 1 1 220px;
  display: flex;
  align-items: center;
  gap: 10px;
}
input[type=\"range\"] {
  width: 100%;
  accent-color: #22d3ee;
}
.time {
  min-width: 92px;
  text-align: right;
  font-variant-numeric: tabular-nums;
  font-size: 12px;
  color: #cbd5e1;
}
.status {
  display: inline-flex;
  gap: 10px;
  align-items: center;
  font-size: 12px;
  color: #cbd5e1;
}
.counter {
  font-variant-numeric: tabular-nums;
}
.loop-wrap {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}
.hint {
  width: 100%;
  font-size: 11px;
  color: rgba(203, 213, 225, 0.74);
}
@media (max-width: 720px) {
  body {
    padding: 10px;
  }
  .player-header {
    flex-wrap: wrap;
  }
  .controls {
    gap: 10px;
  }
  .hint {
    margin-top: -2px;
  }
}
</style>
</head>
<body>
  <main class="player">
    <header class="player-header">
      <div class="title-row">
        <h1 class="title">${title}</h1>
        <span class="badge">Powered by Walkr</span>
      </div>
      <button id="copyLink" class="copy-link" type="button">Copy Frame URL</button>
    </header>
    <section class="frame-display">
      <img id="frame" alt="Walkr capture frame" />
      <div id="loading" class="loading">
        <span id="loadingLabel" class="loading-label">Loading 0 / ${frameData.length}</span>
      </div>
    </section>
    <section class="controls" aria-label="player controls">
      <div class="left-controls">
        <button id="prev" class="control-btn" type="button" aria-label="Previous frame">←</button>
        <button id="playPause" class="control-btn" type="button" aria-label="Play">▶</button>
        <button id="next" class="control-btn" type="button" aria-label="Next frame">→</button>
      </div>
      <div class="progress-wrap">
        <input id="progress" type="range" min="0" max="${maxFrame}" step="1" value="0" />
        <span id="time" class="time">00:00 / 00:00</span>
      </div>
      <div class="status">
        <span id="counter" class="counter">0 / ${frameData.length}</span>
        <label class="loop-wrap"><input id="loop" type="checkbox" checked /> <span>🔁</span></label>
      </div>
      <div class="hint">Shortcuts: Space play/pause, ←/→ step, L loop toggle</div>
    </section>
  </main>
<script>
const frames = ${JSON.stringify(frameData)};
const fps = ${safeFps};
const frameDuration = 1000 / Math.max(1, fps);
const maxFrame = Math.max(frames.length - 1, 0);
const frameImage = document.getElementById("frame");
const progress = document.getElementById("progress");
const playPause = document.getElementById("playPause");
const prev = document.getElementById("prev");
const next = document.getElementById("next");
const counter = document.getElementById("counter");
const loopCheckbox = document.getElementById("loop");
const time = document.getElementById("time");
const copyLink = document.getElementById("copyLink");
const loading = document.getElementById("loading");
const loadingLabel = document.getElementById("loadingLabel");

const loaded = new Array(frames.length).fill(false);
let loadedCount = 0;
let currentFrame = 0;
let playing = false;
let raf = 0;
let lastTick = 0;

const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
const hasInteger = (value) => /^-?\\d+$/.test(value);

const parseFrameFromLocation = () => {
  const url = new URL(window.location.href);
  const queryFrame = url.searchParams.get("frame");
  if (queryFrame && hasInteger(queryFrame)) {
    return Number(queryFrame);
  }

  const hash = window.location.hash.replace(/^#/, "").trim();
  if (!hash) {
    return 0;
  }

  const hashValue = hash.toLowerCase().startsWith("frame=") ? hash.slice(6) : hash;
  if (hasInteger(hashValue)) {
    return Number(hashValue);
  }

  return 0;
};

const formatTime = (seconds) => {
  const safe = Number.isFinite(seconds) ? Math.max(0, seconds) : 0;
  const mins = Math.floor(safe / 60);
  const secs = Math.floor(safe % 60);
  return String(mins).padStart(2, "0") + ":" + String(secs).padStart(2, "0");
};

const updateLoading = () => {
  if (frames.length === 0) {
    loading.classList.remove("hidden");
    loadingLabel.textContent = "No frames";
    return;
  }

  if (loadedCount >= frames.length) {
    loading.classList.add("hidden");
    return;
  }

  loading.classList.remove("hidden");
  loadingLabel.textContent = "Loading " + loadedCount + " / " + frames.length;
};

const setFrameInUrl = () => {
  const url = new URL(window.location.href);
  url.searchParams.set("frame", String(currentFrame));
  url.hash = "";
  history.replaceState(null, "", url.toString());
};

const getShareUrl = () => {
  const url = new URL(window.location.href);
  url.searchParams.set("frame", String(currentFrame));
  url.hash = "";
  return url.toString();
};

const renderFrame = (nextFrame, syncUrl = true) => {
  if (frames.length === 0) {
    progress.value = "0";
    counter.textContent = "0 / 0";
    time.textContent = "00:00 / 00:00";
    frameImage.removeAttribute("src");
    return;
  }

  currentFrame = clamp(nextFrame, 0, maxFrame);
  frameImage.src = frames[currentFrame];
  frameImage.classList.add("is-swapping");
  requestAnimationFrame(() => frameImage.classList.remove("is-swapping"));

  progress.value = String(currentFrame);
  counter.textContent = String(currentFrame + 1) + " / " + String(frames.length);
  time.textContent = formatTime(currentFrame / fps) + " / " + formatTime(maxFrame / fps);

  if (syncUrl) {
    setFrameInUrl();
  }
};

const setPlaying = (nextPlaying) => {
  if (playing === nextPlaying) {
    return;
  }

  playing = nextPlaying;
  playPause.textContent = playing ? "⏸" : "▶";
  playPause.setAttribute("aria-label", playing ? "Pause" : "Play");

  if (playing) {
    lastTick = 0;
    cancelAnimationFrame(raf);
    raf = requestAnimationFrame(tick);
  } else {
    cancelAnimationFrame(raf);
  }
};

const stepFrame = (delta) => {
  if (frames.length === 0) {
    return;
  }

  if (delta === 0) {
    return;
  }

  if (delta < 0 && currentFrame <= 0) {
    if (loopCheckbox.checked) {
      renderFrame(maxFrame);
    } else {
      renderFrame(0);
    }
    return;
  }

  if (delta > 0 && currentFrame >= maxFrame) {
    if (loopCheckbox.checked) {
      renderFrame(0);
    } else {
      renderFrame(maxFrame);
    }
    return;
  }

  renderFrame(currentFrame + delta);
};

const tick = (timestamp) => {
  if (!playing) {
    return;
  }

  if (!lastTick) {
    lastTick = timestamp;
  }

  if (timestamp - lastTick >= frameDuration) {
    const framesToAdvance = Math.floor((timestamp - lastTick) / frameDuration);
    lastTick += framesToAdvance * frameDuration;

    const nextFrame = currentFrame + framesToAdvance;
    if (nextFrame > maxFrame) {
      if (loopCheckbox.checked && frames.length > 0) {
        renderFrame(nextFrame % frames.length);
      } else {
        renderFrame(maxFrame);
        setPlaying(false);
        return;
      }
    } else {
      renderFrame(nextFrame);
    }
  }

  raf = requestAnimationFrame(tick);
};

const preload = () => {
  updateLoading();
  frames.forEach((src, frameIndex) => {
    const image = new Image();
    const onDone = () => {
      if (!loaded[frameIndex]) {
        loaded[frameIndex] = true;
        loadedCount += 1;
        updateLoading();
      }
    };
    image.onload = onDone;
    image.onerror = onDone;
    image.src = src;
  });
};

const copyShareUrl = async () => {
  const url = getShareUrl();
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(url);
    } else {
      throw new Error("clipboard unavailable");
    }
    copyLink.textContent = "Copied";
    setTimeout(() => {
      copyLink.textContent = "Copy Frame URL";
    }, 1200);
  } catch {
    const fallback = document.createElement("textarea");
    fallback.value = url;
    fallback.style.position = "fixed";
    fallback.style.left = "-9999px";
    document.body.appendChild(fallback);
    fallback.focus();
    fallback.select();
    try {
      document.execCommand("copy");
      copyLink.textContent = "Copied";
      setTimeout(() => {
        copyLink.textContent = "Copy Frame URL";
      }, 1200);
    } finally {
      fallback.remove();
    }
  }
};

const initialFrame = clamp(parseFrameFromLocation(), 0, maxFrame);
currentFrame = initialFrame;
renderFrame(initialFrame, false);
preload();
setFrameInUrl();

playPause.addEventListener("click", () => setPlaying(!playing));
prev.addEventListener("click", () => stepFrame(-1));
next.addEventListener("click", () => stepFrame(1));
copyLink.addEventListener("click", () => {
  void copyShareUrl();
});
progress.addEventListener("input", () => {
  const value = Number(progress.value);
  renderFrame(value);
});
document.addEventListener("keydown", (event) => {
  const target = event.target;
  const isInputTarget =
    target instanceof HTMLElement &&
    (target.isContentEditable || target.tagName === "INPUT" || target.tagName === "TEXTAREA");

  if (isInputTarget) {
    return;
  }

  if (event.code === "Space") {
    event.preventDefault();
    setPlaying(!playing);
    return;
  }

  if (event.key === "ArrowLeft") {
    event.preventDefault();
    setPlaying(false);
    stepFrame(-1);
    return;
  }

  if (event.key === "ArrowRight") {
    event.preventDefault();
    setPlaying(false);
    stepFrame(1);
    return;
  }

  if (event.key === "l" || event.key === "L") {
    loopCheckbox.checked = !loopCheckbox.checked;
  }
});
</script>
</body>
</html>`;
}
